on:
  push:
    branches:
      - master
  pull_request:
jobs:
  go-tests:
    name: "Go tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: 'go.mod'
      - name: Run tests
        id: runTests
        run: make test
        env:
          FORM3_CLIENT_ID: ${{ secrets.FORM3_CLIENT_ID }}
          FORM3_CLIENT_SECRET: ${{ secrets.FORM3_CLIENT_SECRET }}
          FORM3_ORGANISATION_ID: ${{ secrets.FORM3_ORGANISATION_ID }}
          FORM3_HOST: https://${{ secrets.FORM3_HOST }}
          FORM3_PRIVATE_KEY: ${{ secrets.FORM3_PRIVATE_KEY }}
          FORM3_PUBLIC_KEY_ID: ${{ secrets.FORM3_PUBLIC_KEY_ID }}
